import type { Metadata } from "next";
import {
  Geist, Gravitas_One
  , Domine
} from "next/font/google";
import "./globals.css";
import 'lenis/dist/lenis.css'
import CustomCursor from '@/components/customCursour'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const GravitasOne = Gravitas_One({
  variable: "--font-gravitas-one",
  subsets: ["latin"],
  weight: "400"
});

const domine = Domine({
  variable: "--font-domine",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Foretech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${GravitasOne.variable} ${domine.variable} antialiased`}
      >
        <CustomCursor />
        {children}
      </body>
    </html>
  );
}
